### ISSUE TITLE
TypeError: cannot serialize nan (type float64) while tree.write

### ISSUE THREAD

**Issue by mansi-aggarwal-2504** [mhiyer/coco-annotations-to-xml#3]
Hello, I am getting an error while writing the xml file: `tree.write(anno_path)`
Entire log:

```
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/xml/etree/ElementTree.py", line 1067, in _escape_cdata
    if "&" in text:
TypeError: argument of type 'numpy.float64' is not iterable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/contextlib.py", line 130, in __exit__
    self.gen.throw(type, value, traceback)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/xml/etree/ElementTree.py", line 799, in _get_writer
    yield file.write
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/xml/etree/ElementTree.py", line 777, in write
    short_empty_elements=short_empty_elements)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/xml/etree/ElementTree.py", line 942, in _serialize_xml
    short_empty_elements=short_empty_elements)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/xml/etree/ElementTree.py", line 942, in _serialize_xml
    short_empty_elements=short_empty_elements)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/xml/etree/ElementTree.py", line 939, in _serialize_xml
    write(_escape_cdata(text))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/xml/etree/ElementTree.py", line 1075, in _escape_cdata
    _raise_serialization_error(text)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/xml/etree/ElementTree.py", line 1058, in _raise_serialization_error
    "cannot serialize %r (type %s)" % (text, type(text).__name__)
TypeError: cannot serialize nan (type float64)
```

How can I resolve this? Thanks in advance!

**Comment by mansi-aggarwal-2504** [comment]
I found out the error. Mentioning steps here in case anyone else faces the same problem. 

Since I have only one class in my dataset, `[category_id]['name']` was null as it was not set while annotating images using VGG Image Annotator, and the field was empty in my json. 

```
"categories":[
      {
         "supercategory":"name",
         "id":1,
         "name":""
      }
   ]

```
Hence, I just added the category name in the csv (although it's null in my json as shown above).

supercategory | id | name
-- | -- | --
name | 1 | flower

Thus, at line 120 `category = df.loc[anno['category_id']]['name']` was null. 
It worked now, after I edited the csv with the class name.

Thank you the repository @mhiyer 👍
